# Generated by Django 4.1.2 on 2022-10-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_value', models.CharField(max_length=20, verbose_name='Цена')),
                ('pc_description', models.CharField(max_length=20, verbose_name='Онписание')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(max_length=20, verbose_name='Услуга')),
                ('pr_old_price', models.CharField(max_length=20, verbose_name='Старая цена')),
                ('pr_price', models.CharField(max_length=20, verbose_name='Новая цена')),
            ],
        ),
    ]
