# Generated by Django 4.1.2 on 2022-10-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Цены', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='pricecard',
            name='pc_description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='pr_old_price',
            field=models.CharField(max_length=200, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='pr_price',
            field=models.CharField(max_length=200, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='pt_title',
            field=models.CharField(max_length=200, verbose_name='Услуга'),
        ),
    ]
